### PR TITLE
EIP 18 - rerun button

### PR DESCRIPTION
**Pull request by carlospzurita**
Added a rerun button on the test reports. Added on mobileRouter.js the logic to handle the test objects

### CODE REVIEW

**Comment by carlospzurita** [comment]
The conflict that appears is caused by the use of tabs instead of whitespaces. The application of gradlew spotlessApply solves this problema, but marks 41 files as modified by the commit. ¿Should we apply the gradle script?

**Comment by carlospzurita** [comment]
As far as we see, it has been planned for milestone 2.1.0.
Just to clarify, from our point of view, pending conflicts must be addressed by the TC at the time of integration.
If any additional action is needed from our side, please, let us know.

**Comment by jonherrmann** [comment]
> ¿Should we apply the gradle script?

Hi Carlos, sorry did not see the comment before.

> As far as we see, it has been planned for milestone 2.1.0.
Just to clarify, from our point of view, pending conflicts must be addressed by the TC at the time of integration. If any additional action is needed from our side, please, let us know.

I don't know if I'm getting this right. At first I thought there was a problem with the next branch, so i pulled the PR from the guadaltel repo and created a [PR](https://github.com/etf-validator/etf-webapp/pull/200). Before I created the PR, I pulled from the 'next' branch into my local EIP-18 branch, merged the conflicting 'TestObjectController.java' file and run 'spotlessApply' afterwards. This worked and as far as i can see, this is the problem with this PR and [EIP-48](https://github.com/etf-validator/etf-webapp/pull/193). Please try these steps with the EIP-48 PR.

**Comment by carlospzurita** [comment]
The codacy review points to JS good practices and compliance with EcmaScript. Should we solve them for the PR, or is it okay as it is?

**Comment by carlospzurita** [comment]
We added a change on this PR after we detected a malfunction in our solution, and following your recommendations, we merged the `next` branch on this one and applied `./gradlew spotlessApply` . After that, several issues arised from the quality review, many of them not even from new code. What should we do to fix this?

**Pull request merged**
